const Data = {
  CATEGORIES: [
    { title: 'all', value: '' },
    { title: 'general knowledge', value: '&category=9' },
    { title: 'books', value: '&category=10' },
    { title: 'film', value: '&category=11' },
    { title: 'music', value: '&category=12' },
    { title: 'Musicals & Theatres', value: '&category=13' },
    { title: 'Television', value: '&category=14' },
    { title: 'Video Games', value: '&category=15' },
    { title: 'Board Games', value: '&category=16' },
    { title: 'Science & Nature', value: '&category=17' },
    { title: 'Computers', value: '&category=18' },
    { title: 'Mathematics', value: '&category=19' },
    { title: 'Mythology', value: '&category=20' },
    { title: 'Sports', value: '&category=21' },
    { title: 'Geography', value: '&category=22' },
    { title: 'History', value: '&category=23' },
    { title: 'Politics', value: '&category=24' },
    { title: 'Art', value: '&category=25' },
    { title: 'Celebrities', value: '&category=26' },
    { title: 'Animals', value: '&category=27' },
    { title: 'Vehicles', value: '&category=28' },
    { title: 'Comics', value: '&category=29' },
    { title: 'Gadgets', value: '&category=30' },
    { title: 'Anime & Manga', value: '&category=31' },
    { title: 'Cartoon & Animation', value: '&category=32' },
  ],
  DIFFICULTY: [
    { title: 'all', value: '' },
    { title: 'easy', value: '&difficulty=easy' },
    { title: 'medium', value: '&difficulty=medium' },
    { title: 'hard', value: '&difficulty=hard' },
  ],
  NUMBEROFQUESTIONS: [
    { title: 10, value: 'amount=10' },
    { title: 20, value: 'amount=20' },
    { title: 30, value: 'amount=30' },
    { title: 40, value: 'amount=40' },
  ],
};

export default Data;
