const Data = {
  CATEGORIES: [
    { title: 'all', value: '' },
    { title: 'general knowledge', value: '&category=9' },
    { title: 'books', value: '&category=10' },
    { title: 'film', value: '&category=11' },
    { title: 'music', value: '&category=12' },
    { title: 'Musicals & Theatres', value: '&category=13' },
    { title: 'Television', value: '&category=14' },
    { title: 'Video Games', value: '&category=15' },
    { title: 'Board Games', value: '&category=16' },
    { title: 'Science & Nature', value: '&category=17' },
    { title: 'Computers', value: '&category=18' },
    { title: 'Mathematics', value: '&category=19' },
    { title: 'Mythology', value: '&category=20' },
    { title: 'Sports', value: '&category=21' },
    { title: 'Geography', value: '&category=22' },
    { title: 'History', value: '&category=23' },
    { title: 'Politics', value: '&category=24' },
    { title: 'Art', value: '&category=25' },
    { title: 'Celebrities', value: '&category=26' },
    { title: 'Animals', value: '&category=27' },
    { title: 'Vehicles', value: '&category=28' },
    { title: 'Comics', value: '&category=29' },
    { title: 'Gadgets', value: '&category=30' },
    { title: 'Anime & Manga', value: '&category=31' },
    { title: 'Cartoon & Animation', value: '&category=32' },
  ],
  DIFFICULTY: [
    { title: 'all', value: '' },
    { title: 'easy', value: '&difficulty=easy' },
    { title: 'medium', value: '&difficulty=medium' },
    { title: 'hard', value: '&difficulty=hard' },
  ],
  NUMBEROFQUESTIONS: [
    { title: 10, value: 'amount=10' },
    { title: 20, value: 'amount=20' },
    { title: 30, value: 'amount=30' },
    { title: 40, value: 'amount=40' },
  ],
  TESTRESPONSEDATA: [
    {
      category: 'Geography',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What are the four corner states of the US?',
      correct_answer: 'Utah, Colorado, Arizona, New Mexico',
      incorrect_answers: [
        'Oregon, Idaho, Nevada, Utah',
        'Kansas, Oklahoma, Arkansas, Louisiana',
        'South Dakota, Minnesota, Nebraska, Iowa',
      ],
    },
    {
      category: 'Science & Nature',
      type: 'multiple',
      difficulty: 'hard',
      question:
        'All of the following human genetic haplogroup names are shared between Y-chromosome and mitochondrial DNA haplogroups EXCEPT:',
      correct_answer: 'Haplogroup U',
      incorrect_answers: ['Haplogroup L', 'Haplogroup T', 'Haplogroup J'],
    },
    {
      category: 'Entertainment: Television',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Which of these Bojack Horseman characters is a human?',
      correct_answer: 'Todd Chavez',
      incorrect_answers: [
        'Lennie Turtletaub',
        'Princess Carolyn',
        'Tom Jumbo-Grumbo',
      ],
    },
    {
      category: 'Entertainment: Comics',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What was the name of the first Robin in the Batman comics?',
      correct_answer: 'Dick Grayson',
      incorrect_answers: ['Bruce Wayne', 'Jason Todd', 'Tim Drake'],
    },
    {
      category: 'History',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What nationality was sultan Saladin?',
      correct_answer: 'Kurdish',
      incorrect_answers: ['Arab', 'Egyptian', 'Syrian'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'How many differently shaped Tetris pieces are there?',
      correct_answer: '7',
      incorrect_answers: ['5', '6', '8'],
    },
    {
      category: 'Entertainment: Books',
      type: 'multiple',
      difficulty: 'easy',
      question:
        'What is the title of the first Sherlock Holmes book by Arthur Conan Doyle?',
      correct_answer: 'A Study in Scarlet',
      incorrect_answers: [
        'The Sign of the Four',
        'A Case of Identity',
        'The Doings of Raffles Haw',
      ],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What does LTS stand for in the software market?',
      correct_answer: 'Long Term Support',
      incorrect_answers: [
        'Long Taco Service',
        'Ludicrous Transfer Speed',
        'Ludicrous Turbo Speed',
      ],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What does &quot;LCD&quot; stand for?',
      correct_answer: 'Liquid Crystal Display',
      incorrect_answers: [
        'Language Control Design',
        'Last Common Difference',
        'Long Continuous Design',
      ],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      question:
        'In the game Tom Clancy&#039;s Rainbow 6 Siege, what organization is Valkyrie from?',
      correct_answer: 'Navy Seals',
      incorrect_answers: ['S.A.S', 'G.I.G.N', 'F.B.I'],
    },
  ],
};

export default Data;
