const Data = {
  CATEGORIES: [
    { title: 'all', value: '' },
    { title: 'general knowledge', value: '&category=9' },
    { title: 'books', value: '&category=10' },
    { title: 'film', value: '&category=11' },
    { title: 'music', value: '&category=12' },
    { title: 'Musicals & Theatres', value: '&category=13' },
    { title: 'Television', value: '&category=14' },
    { title: 'Video Games', value: '&category=15' },
    { title: 'Board Games', value: '&category=16' },
    { title: 'Science & Nature', value: '&category=17' },
    { title: 'Computers', value: '&category=18' },
    { title: 'Mathematics', value: '&category=19' },
    { title: 'Mythology', value: '&category=20' },
    { title: 'Sports', value: '&category=21' },
    { title: 'Geography', value: '&category=22' },
    { title: 'History', value: '&category=23' },
    { title: 'Politics', value: '&category=24' },
    { title: 'Art', value: '&category=25' },
    { title: 'Celebrities', value: '&category=26' },
    { title: 'Animals', value: '&category=27' },
    { title: 'Vehicles', value: '&category=28' },
    { title: 'Comics', value: '&category=29' },
    { title: 'Gadgets', value: '&category=30' },
    { title: 'Anime & Manga', value: '&category=31' },
    { title: 'Cartoon & Animation', value: '&category=32' },
  ],
  DIFFICULTY: [
    { title: 'all', value: '' },
    { title: 'easy', value: '&difficulty=easy' },
    { title: 'medium', value: '&difficulty=medium' },
    { title: 'hard', value: '&difficulty=hard' },
  ],
  NUMBEROFQUESTIONS: [
    { title: 10, value: 'amount=10' },
    { title: 20, value: 'amount=20' },
    { title: 30, value: 'amount=30' },
    { title: 40, value: 'amount=40' },
  ],
  TESTRESPONSEDATA: [
    {
      category: 'Geography',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What are the four corner states of the US?',
      correct_answer: 'Utah, Colorado, Arizona, New Mexico',
      incorrect_answers: [
        'Oregon, Idaho, Nevada, Utah',
        'Kansas, Oklahoma, Arkansas, Louisiana',
        'South Dakota, Minnesota, Nebraska, Iowa',
      ],
    },
    {
      category: 'Science & Nature',
      type: 'multiple',
      difficulty: 'hard',
      question:
        'All of the following human genetic haplogroup names are shared between Y-chromosome and mitochondrial DNA haplogroups EXCEPT:',
      correct_answer: 'Haplogroup U',
      incorrect_answers: ['Haplogroup L', 'Haplogroup T', 'Haplogroup J'],
    },
    {
      category: 'Entertainment: Television',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Which of these Bojack Horseman characters is a human?',
      correct_answer: 'Todd Chavez',
      incorrect_answers: [
        'Lennie Turtletaub',
        'Princess Carolyn',
        'Tom Jumbo-Grumbo',
      ],
    },
    {
      category: 'Entertainment: Comics',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What was the name of the first Robin in the Batman comics?',
      correct_answer: 'Dick Grayson',
      incorrect_answers: ['Bruce Wayne', 'Jason Todd', 'Tim Drake'],
    },
    {
      category: 'History',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What nationality was sultan Saladin?',
      correct_answer: 'Kurdish',
      incorrect_answers: ['Arab', 'Egyptian', 'Syrian'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'easy',
      question: 'How many differently shaped Tetris pieces are there?',
      correct_answer: '7',
      incorrect_answers: ['5', '6', '8'],
    },
    {
      category: 'Entertainment: Books',
      type: 'multiple',
      difficulty: 'easy',
      question:
        'What is the title of the first Sherlock Holmes book by Arthur Conan Doyle?',
      correct_answer: 'A Study in Scarlet',
      incorrect_answers: [
        'The Sign of the Four',
        'A Case of Identity',
        'The Doings of Raffles Haw',
      ],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What does LTS stand for in the software market?',
      correct_answer: 'Long Term Support',
      incorrect_answers: [
        'Long Taco Service',
        'Ludicrous Transfer Speed',
        'Ludicrous Turbo Speed',
      ],
    },
    {
      category: 'Science: Computers',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What does &quot;LCD&quot; stand for?',
      correct_answer: 'Liquid Crystal Display',
      incorrect_answers: [
        'Language Control Design',
        'Last Common Difference',
        'Long Continuous Design',
      ],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'multiple',
      difficulty: 'medium',
      question:
        'In the game Tom Clancy&#039;s Rainbow 6 Siege, what organization is Valkyrie from?',
      correct_answer: 'Navy Seals',
      incorrect_answers: ['S.A.S', 'G.I.G.N', 'F.B.I'],
    },
  ],
};

//data placeholder for recipe app:
const DataRecipeApp = {
  recipeList: [
    {
      id: 624920,
      title: 'Mini Smoked Salmon & Pesto Yogurt Phyllo Bites',
      image: 'https://spoonacular.com/recipeImages/624920-312x231.jpg',
      imageType: 'jpg',
      usedIngredientCount: 3,
      missedIngredientCount: 3,
      missedIngredients: [
        {
          id: 93698,
          amount: 3,
          unit: 'tbsp',
          unitLong: 'tablespoons',
          unitShort: 'Tbsp',
          aisle: 'Pasta and Rice',
          name: 'basil pesto',
          original: '3 tbsp basil pesto',
          originalString: '3 tbsp basil pesto',
          originalName: 'basil pesto',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/basil-pesto.png',
        },
        {
          id: 93817,
          amount: 2,
          unit: 'boxes',
          unitLong: 'boxes',
          unitShort: 'box',
          aisle: 'Refrigerated;Frozen',
          name: 'fillo shells',
          original:
            '2 boxes Athens Mini Fillo shells (30 shells total), defrosted',
          originalString:
            '2 boxes Athens Mini Fillo shells (30 shells total), defrosted',
          originalName: 'Athens Mini Fillo shells (30 shells total), defrosted',
          metaInformation: ['mini', '(30 shells total)'],
          meta: ['mini', '(30 shells total)'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/mini-phyllo-shells.png',
        },
        {
          id: 11291,
          amount: 1,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'green onion',
          original: '1 green onion (scallion), thinly sliced',
          originalString: '1 green onion (scallion), thinly sliced',
          originalName: 'green onion (scallion), thinly sliced',
          metaInformation: ['thinly sliced', '(scallion)'],
          meta: ['thinly sliced', '(scallion)'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/spring-onions.jpg',
        },
      ],
      usedIngredients: [
        {
          id: 1011256,
          amount: 0.25,
          unit: 'cup',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'non-fat greek yogurt',
          original: '¼ cup non-fat Greek yogurt',
          originalString: '¼ cup non-fat Greek yogurt',
          originalName: 'non-fat Greek yogurt',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/plain-yogurt.jpg',
        },
        {
          id: 15077,
          amount: 4,
          unit: 'oz',
          unitLong: 'ounces',
          unitShort: 'oz',
          aisle: 'Seafood',
          name: 'smoked salmon',
          original: '4 oz. smoked salmon, cut into 30 pieces',
          originalString: '4 oz. smoked salmon, cut into 30 pieces',
          originalName: 'smoked salmon, cut into 30 pieces',
          metaInformation: ['smoked', 'cut into 30 pieces'],
          meta: ['smoked', 'cut into 30 pieces'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/smoked-salmon.png',
        },
        {
          id: 11529,
          amount: 0.5,
          unit: 'cup',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Produce',
          name: 'tomatoes',
          original: '½ cup diced tomatoes (no seeds)',
          originalString: '½ cup diced tomatoes (no seeds)',
          originalName: 'diced tomatoes (no seeds)',
          metaInformation: ['diced', '(no seeds)'],
          meta: ['diced', '(no seeds)'],
          extendedName: 'diced tomatoes',
          image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
        },
      ],
      unusedIngredients: [
        {
          id: 15076,
          amount: 1,
          unit: 'serving',
          unitLong: 'serving',
          unitShort: 'serving',
          aisle: 'Seafood',
          name: 'salmon',
          original: 'salmon',
          originalString: 'salmon',
          originalName: 'salmon',
          metaInformation: [],
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/salmon.png',
        },
        {
          id: 1116,
          amount: 1,
          unit: 'serving',
          unitLong: 'serving',
          unitShort: 'serving',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'yogurt',
          original: 'yogurt',
          originalString: 'yogurt',
          originalName: 'yogurt',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/plain-yogurt.jpg',
        },
      ],
      likes: 18,
    },
    {
      id: 195870,
      title: 'Smoked Salmon Club Sandwich',
      image: 'https://spoonacular.com/recipeImages/195870-312x231.jpg',
      imageType: 'jpg',
      usedIngredientCount: 3,
      missedIngredientCount: 4,
      missedIngredients: [
        {
          id: 11250,
          amount: 2,
          unit: 'leaves',
          unitLong: 'leaves',
          unitShort: 'leaf',
          aisle: 'Produce',
          name: 'butter lettuce',
          original: '2-3 leaves butter lettuce, torn into 3-4 pieces',
          originalString: '2-3 leaves butter lettuce, torn into 3-4 pieces',
          originalName: 'butter lettuce, torn into 3-4 pieces',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/Butter-or-Boston-Bibb-lettuce.jpg',
        },
        {
          id: 2045,
          amount: 1,
          unit: 'tsp',
          unitLong: 'teaspoon',
          unitShort: 'tsp',
          aisle: 'Produce;Spices and Seasonings',
          name: 'fresh dill',
          original: '1 tsp minced fresh dill',
          originalString: '1 tsp minced fresh dill',
          originalName: 'minced fresh dill',
          metaInformation: ['fresh', 'minced'],
          meta: ['fresh', 'minced'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/dill.jpg',
        },
        {
          id: 1031,
          amount: 1,
          unit: 'tbsp',
          unitLong: 'tablespoon',
          unitShort: 'Tbsp',
          aisle: 'Cheese',
          name: 'neufchatel cheese',
          original: '1 tbsp cream cheese or Neufchatel cheese',
          originalString: '1 tbsp cream cheese or Neufchatel cheese',
          originalName: 'cream cheese or Neufchatel cheese',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/neufchatel.jpg',
        },
        {
          id: 18069,
          amount: 3,
          unit: 'slices',
          unitLong: 'slices',
          unitShort: 'slice',
          aisle: 'Bakery/Bread',
          name: 'white bread',
          original: '3 slices white bread',
          originalString: '3 slices white bread',
          originalName: 'white bread',
          metaInformation: ['white'],
          meta: ['white'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/white-bread.jpg',
        },
      ],
      usedIngredients: [
        {
          id: 1011256,
          amount: 2,
          unit: 'tbsp',
          unitLong: 'tablespoons',
          unitShort: 'Tbsp',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'nonfat greek yogurt',
          original: '2 tbsp lowfat or nonfat Greek yogurt',
          originalString: '2 tbsp lowfat or nonfat Greek yogurt',
          originalName: 'lowfat or nonfat Greek yogurt',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/plain-yogurt.jpg',
        },
        {
          id: 15077,
          amount: 4,
          unit: 'oz',
          unitLong: 'ounces',
          unitShort: 'oz',
          aisle: 'Seafood',
          name: 'smoked salmon',
          original: '4 oz smoked salmon',
          originalString: '4 oz smoked salmon',
          originalName: 'smoked salmon',
          metaInformation: ['smoked'],
          meta: ['smoked'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/smoked-salmon.png',
        },
        {
          id: 11529,
          amount: 2,
          unit: 'slices',
          unitLong: 'slices',
          unitShort: 'slice',
          aisle: 'Produce',
          name: 'tomato',
          original: '2-3 slices ripe red tomato',
          originalString: '2-3 slices ripe red tomato',
          originalName: 'ripe red tomato',
          metaInformation: ['red', 'ripe'],
          meta: ['red', 'ripe'],
          extendedName: 'red tomato',
          image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
        },
      ],
      unusedIngredients: [
        {
          id: 15076,
          amount: 1,
          unit: 'serving',
          unitLong: 'serving',
          unitShort: 'serving',
          aisle: 'Seafood',
          name: 'salmon',
          original: 'salmon',
          originalString: 'salmon',
          originalName: 'salmon',
          metaInformation: [],
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/salmon.png',
        },
        {
          id: 1116,
          amount: 1,
          unit: 'serving',
          unitLong: 'serving',
          unitShort: 'serving',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'yogurt',
          original: 'yogurt',
          originalString: 'yogurt',
          originalName: 'yogurt',
          metaInformation: [],
          meta: [],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/plain-yogurt.jpg',
        },
      ],
      likes: 112,
    },
    {
      id: 87074,
      title: 'Salmon With Yogurt Dill Sauce',
      image: 'https://spoonacular.com/recipeImages/87074-312x231.jpg',
      imageType: 'jpg',
      usedIngredientCount: 3,
      missedIngredientCount: 4,
      missedIngredients: [
        {
          id: 2045,
          amount: 2,
          unit: 'tablespoons',
          unitLong: 'tablespoons',
          unitShort: 'Tbsp',
          aisle: 'Produce;Spices and Seasonings',
          name: 'fresh dill',
          original: '2 tablespoons dill (fresh, chopped)',
          originalString: '2 tablespoons dill (fresh, chopped)',
          originalName: 'dill (fresh, chopped)',
          metaInformation: ['fresh', 'chopped', '(, )'],
          meta: ['fresh', 'chopped', '(, )'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/dill.jpg',
        },
        {
          id: 11215,
          amount: 6,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'garlic cloves',
          original: '6 garlic cloves (minced)',
          originalString: '6 garlic cloves (minced)',
          originalName: 'garlic cloves (minced)',
          metaInformation: ['minced', '()'],
          meta: ['minced', '()'],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/garlic.png',
        },
        {
          id: 9195,
          amount: 20,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Canned and Jarred',
          name: 'olives',
          original: '20 olives (kalamata-pitted-coarsely chopped)',
          originalString: '20 olives (kalamata-pitted-coarsely chopped)',
          originalName: 'olives (kalamata-pitted-coarsely chopped)',
          metaInformation: ['chopped', '(kalamata-pitted-coarsely )'],
          meta: ['chopped', '(kalamata-pitted-coarsely )'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/olives-mixed.jpg',
        },
        {
          id: 2027,
          amount: 1.5,
          unit: 'teaspoons',
          unitLong: 'teaspoons',
          unitShort: 'tsp',
          aisle: 'Produce;Spices and Seasonings',
          name: 'oregano',
          original: '1 1/2 teaspoons oregano',
          originalString: '1 1/2 teaspoons oregano',
          originalName: 'oregano',
          metaInformation: [],
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/oregano.jpg',
        },
      ],
      usedIngredients: [
        {
          id: 10311529,
          amount: 15,
          unit: '',
          unitLong: '',
          unitShort: '',
          aisle: 'Produce',
          name: 'cherry tomatoes',
          original: '15 cherry tomatoes (chopped)',
          originalString: '15 cherry tomatoes (chopped)',
          originalName: 'cherry tomatoes (chopped)',
          metaInformation: ['chopped', '()'],
          meta: ['chopped', '()'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/cherry-tomatoes.png',
        },
        {
          id: 15076,
          amount: 3,
          unit: 'lbs',
          unitLong: 'pounds',
          unitShort: 'lb',
          aisle: 'Seafood',
          name: 'salmon fillets',
          original: '3 lbs salmon fillets',
          originalString: '3 lbs salmon fillets',
          originalName: 'salmon fillets',
          metaInformation: [],
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/salmon.png',
        },
        {
          id: 1116,
          amount: 1.25,
          unit: 'cups',
          unitLong: 'cups',
          unitShort: 'cup',
          aisle: 'Milk, Eggs, Other Dairy',
          name: 'yogurt',
          original: '1 1/4 cups yogurt (dannon-plain)',
          originalString: '1 1/4 cups yogurt (dannon-plain)',
          originalName: 'yogurt (dannon-plain)',
          metaInformation: ['(dannon-plain)'],
          meta: ['(dannon-plain)'],
          image:
            'https://spoonacular.com/cdn/ingredients_100x100/plain-yogurt.jpg',
        },
      ],
      unusedIngredients: [
        {
          id: 11529,
          amount: 1,
          unit: 'serving',
          unitLong: 'serving',
          unitShort: 'serving',
          aisle: 'Produce',
          name: 'tomato',
          original: 'tomato',
          originalString: 'tomato',
          originalName: 'tomato',
          metaInformation: [],
          meta: [],
          image: 'https://spoonacular.com/cdn/ingredients_100x100/tomato.png',
        },
      ],
      likes: 0,
    },
  ],
  singleRecipe: {
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 10,
    gaps: 'no',
    lowFodmap: false,
    aggregateLikes: 112,
    spoonacularScore: 95,
    healthScore: 35,
    creditsText: 'The Shiksa in the Kitchen',
    sourceName: 'The Shiksa in the Kitchen',
    pricePerServing: 548.31,
    extendedIngredients: [
      {
        id: 11250,
        aisle: 'Produce',
        image: 'Butter-or-Boston-Bibb-lettuce.jpg',
        consistency: 'solid',
        name: 'butter lettuce',
        nameClean: 'butter lettuce',
        original: '2-3 leaves butter lettuce, torn into 3-4 pieces',
        originalString: '2-3 leaves butter lettuce, torn into 3-4 pieces',
        originalName: 'butter lettuce, torn into 3-4 pieces',
        amount: 2,
        unit: 'leaves',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2,
            unitShort: 'leaf',
            unitLong: 'leaves',
          },
          metric: {
            amount: 2,
            unitShort: 'leaf',
            unitLong: 'leaves',
          },
        },
      },
      {
        id: 2045,
        aisle: 'Produce;Spices and Seasonings',
        image: 'dill.jpg',
        consistency: 'solid',
        name: 'fresh dill',
        nameClean: 'dill',
        original: '1 tsp minced fresh dill',
        originalString: '1 tsp minced fresh dill',
        originalName: 'minced fresh dill',
        amount: 1,
        unit: 'tsp',
        meta: ['fresh', 'minced'],
        metaInformation: ['fresh', 'minced'],
        measures: {
          us: {
            amount: 1,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
          metric: {
            amount: 1,
            unitShort: 'tsp',
            unitLong: 'teaspoon',
          },
        },
      },
      {
        id: 1031,
        aisle: 'Cheese',
        image: 'neufchatel.jpg',
        consistency: 'solid',
        name: 'neufchatel cheese',
        nameClean: 'neufchatel',
        original: '1 tbsp cream cheese or Neufchatel cheese',
        originalString: '1 tbsp cream cheese or Neufchatel cheese',
        originalName: 'cream cheese or Neufchatel cheese',
        amount: 1,
        unit: 'tbsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
          metric: {
            amount: 1,
            unitShort: 'Tbsp',
            unitLong: 'Tbsp',
          },
        },
      },
      {
        id: 1011256,
        aisle: 'Milk, Eggs, Other Dairy',
        image: 'plain-yogurt.jpg',
        consistency: 'liquid',
        name: 'nonfat greek yogurt',
        nameClean: 'fat free greek yogurt',
        original: '2 tbsp lowfat or nonfat Greek yogurt',
        originalString: '2 tbsp lowfat or nonfat Greek yogurt',
        originalName: 'lowfat or nonfat Greek yogurt',
        amount: 2,
        unit: 'tbsp',
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
          metric: {
            amount: 2,
            unitShort: 'Tbsps',
            unitLong: 'Tbsps',
          },
        },
      },
      {
        id: 15077,
        aisle: 'Seafood',
        image: 'smoked-salmon.png',
        consistency: 'solid',
        name: 'smoked salmon',
        nameClean: 'smoked salmon',
        original: '4 oz smoked salmon',
        originalString: '4 oz smoked salmon',
        originalName: 'smoked salmon',
        amount: 4,
        unit: 'oz',
        meta: ['smoked'],
        metaInformation: ['smoked'],
        measures: {
          us: {
            amount: 4,
            unitShort: 'oz',
            unitLong: 'ounces',
          },
          metric: {
            amount: 113.398,
            unitShort: 'g',
            unitLong: 'grams',
          },
        },
      },
      {
        id: 11529,
        aisle: 'Produce',
        image: 'tomato.png',
        consistency: 'solid',
        name: 'tomato',
        nameClean: 'tomato',
        original: '2-3 slices ripe red tomato',
        originalString: '2-3 slices ripe red tomato',
        originalName: 'ripe red tomato',
        amount: 2,
        unit: 'slices',
        meta: ['red', 'ripe'],
        metaInformation: ['red', 'ripe'],
        measures: {
          us: {
            amount: 2,
            unitShort: 'slice',
            unitLong: 'slices',
          },
          metric: {
            amount: 2,
            unitShort: 'slice',
            unitLong: 'slices',
          },
        },
      },
      {
        id: 18069,
        aisle: 'Bakery/Bread',
        image: 'white-bread.jpg',
        consistency: 'solid',
        name: 'white bread',
        nameClean: 'white bread',
        original: '3 slices white bread',
        originalString: '3 slices white bread',
        originalName: 'white bread',
        amount: 3,
        unit: 'slices',
        meta: ['white'],
        metaInformation: ['white'],
        measures: {
          us: {
            amount: 3,
            unitShort: 'slice',
            unitLong: 'slices',
          },
          metric: {
            amount: 3,
            unitShort: 'slice',
            unitLong: 'slices',
          },
        },
      },
    ],
    id: 195870,
    title: 'Smoked Salmon Club Sandwich',
    readyInMinutes: 10,
    servings: 1,
    sourceUrl: 'http://theshiksa.com/2013/05/29/smoked-salmon-club-sandwich/',
    image: 'https://spoonacular.com/recipeImages/195870-556x370.jpg',
    imageType: 'jpg',
    summary:
      'Need a <b>pescatarian main course</b>? Smoked Salmon Club Sandwich could be a tremendous recipe to try. This recipe serves 1. One portion of this dish contains about <b>33g of protein</b>, <b>11g of fat</b>, and a total of <b>400 calories</b>. For <b>$5.49 per serving</b>, this recipe <b>covers 31%</b> of your daily requirements of vitamins and minerals. 112 people were impressed by this recipe. Head to the store and pick up nonfat greek yogurt, dill, salmon, and a few other things to make it today. To use up the nonfat greek yogurt you could follow this main course with the <a href="https://spoonacular.com/recipes/greek-yogurt-biscuits-584823">Greek Yogurt Biscuits</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/smoked-salmon-club-sandwich-542333">Smoked Salmon Club Sandwich</a>, <a href="https://spoonacular.com/recipes/smoked-salmon-club-sandwich-533141">Smoked Salmon Club Sandwich</a>, and <a href="https://spoonacular.com/recipes/smoked-portobello-club-sandwich-758833">Smoked Portobello Club Sandwich</a> for similar recipes.',
    cuisines: [],
    dishTypes: [],
    diets: ['pescatarian'],
    occasions: [],
    winePairing: {
      pairedWines: ['chardonnay', 'pinot noir', 'sauvignon blanc'],
      pairingText:
        'Salmon can be paired with Chardonnay, Pinot Noir, and Sauvignon Blanc. To decide on white or red, you should consider your seasoning and sauces. Chardonnay is a great friend to buttery, creamy dishes, while sauvignon blanc can complement herb or citrus-centric dishes. A light-bodied, low-tannin red such as the pinot noir goes great with broiled or grilled salmon. You could try Vie di Romans Chardonnay. Reviewers quite like it with a 4.6 out of 5 star rating and a price of about 33 dollars per bottle.',
      productMatches: [
        {
          id: 445863,
          title: 'Vie di Romans Chardonnay',
          description: 'A dry wine made with 100% Chardonnay grapes.',
          price: '$32.99',
          imageUrl: 'https://spoonacular.com/productImages/445863-312x231.jpg',
          averageRating: 0.9199999999999999,
          ratingCount: 5,
          score: 0.8574999999999999,
          link: 'https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fvie-di-romans-chardonnay-2015%2F319683',
        },
      ],
    },
    instructions:
      'Save RecipePrint Recipe                          Smoked Salmon Club Sandwich                                        Ingredients3 slices white bread2 tbsp lowfat or nonfat Greek yogurt1 tbsp cream cheese or Neufchatel cheese1 tsp minced fresh dillDash of salt4 oz smoked salmon2-3 leaves butter lettuce, torn into 3-4 pieces2-3 slices ripe red tomato1 tsp capers (optional)You will also needtoothpicks (optional)                                                        Total Time: 10 Minutes          Servings: 1          Kosher Key: Dairy',
    analyzedInstructions: [
      {
        name: '',
        steps: [
          {
            number: 1,
            step: 'Save Recipe',
            ingredients: [],
            equipment: [],
          },
          {
            number: 2,
            step: 'Print Recipe',
            ingredients: [],
            equipment: [],
          },
          {
            number: 3,
            step: 'Smoked Salmon Club Sandwich',
            ingredients: [
              {
                id: 15077,
                name: 'smoked salmon',
                localizedName: 'smoked salmon',
                image: 'smoked-salmon.png',
              },
            ],
            equipment: [],
          },
          {
            number: 4,
            step: 'Ingredients3 slices white bread2 tbsp lowfat or nonfat Greek yogurt1 tbsp cream cheese or Neufchatel cheese1 tsp minced fresh dill',
            ingredients: [
              {
                id: 1017,
                name: 'cream cheese',
                localizedName: 'cream cheese',
                image: 'cream-cheese.jpg',
              },
              {
                id: 2045,
                name: 'fresh dill',
                localizedName: 'fresh dill',
                image: 'dill.jpg',
              },
              {
                id: 1031,
                name: 'neufchatel',
                localizedName: 'neufchatel',
                image: 'neufchatel.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: 'Dash of salt4 oz smoked salmon2-3 leaves butter lettuce, torn into 3-4 pieces2-3 slices ripe red tomato1 tsp capers (optional)You will also needtoothpicks (optional)',
            ingredients: [
              {
                id: 11250,
                name: 'butter lettuce',
                localizedName: 'butter lettuce',
                image: 'Butter-or-Boston-Bibb-lettuce.jpg',
              },
              {
                id: 2054,
                name: 'capers',
                localizedName: 'capers',
                image: 'capers.jpg',
              },
            ],
            equipment: [],
          },
          {
            number: 6,
            step: 'Total Time: 10 Minutes',
            ingredients: [],
            equipment: [],
          },
          {
            number: 7,
            step: 'Servings: 1',
            ingredients: [],
            equipment: [],
          },
          {
            number: 8,
            step: 'Kosher Key: Dairy',
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
  },
};

export default Data;
